#http://localhost/api/v1/swagger-ui/index.html
server:
  port: 80
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
spring:
  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/DistaDB'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    open-in-view: false
#    database-platform: org.hibernate.dialect.OracleDialect
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#
#  datasource:
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      maximum-pool-size: 10
#    url: jdbc:oracle:thin:@192.168.0.101:1521/XEPDB1
#    username: SYSTEM
#    password: root
#    driver-class-name: oracle.jdbc.OracleDriver
#    type: com.zaxxer.hikari.HikariDataSource
#  main:
#    allow-bean-definition-overriding: true
#    lazy-initialization: true


