#http://localhost/api/v1/swagger-ui/index.html
server:
  port: 80
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XEPDB1
    username: SYSTEM
    password: root
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      s-q-l-for-validate-connection: select * from dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.Oracle12gDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

